GET http://localhost:5000/api/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAwZDg2ZDc5OWU5Y2NjMTlmNWExNDgiLCJlbWFpbCI6ImsuZG9lQG1haWwuY29tIiwiaWF0IjoxNjc4MTI0MDA2LCJleHAiOjE2NzgxMjc2MDZ9.uKmD85bcl-fNDhsPNTGxXxCzuPu8NVUkmlRYqLiEzEs HTTP/1.1