POST http://localhost:5000/api/users/sign-up HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kate",
    "lastName": "Doe",
    "birthday": "1985-01-01",
    "email": "k.doe@mail.com",
    "password": "ydshdchs737gfj"
}