export const ACTION_TYPES = {
    COUNTER_INCREMENT: 'COUNTER_INCREMENT',
    COUNTER_DECREMENT: 'COUNTER_DECREMENT',
    SET_COUNTER_STEP: 'SET_COUNTER_STEP',
    REQUEST_COUNTER_FETCHING: 'REQUEST_COUNTER_FETCHING',
    REQUEST_COUNTER_SUCCESS: 'REQUEST_COUNTER_SUCCESS',
    REQUEST_COUNTER_ERROR: 'REQUEST_COUNTER_ERROR'
}